<a href='https://nevtik.org'><img src='https://drive.google.com/uc?export=view&id=1_IP9MG7FF0p0Ah9q4ptR46StNwCSKFJV' style= width:100px></a>

# NumPy

NumPy (Numerical Python) adalah library Python yang fokus pada scientific computing. NumPy memiliki kemampuan untuk membentuk objek N-dimensional array, yang mirip dengan list pada Python. Keunggulan NumPy array dibandingkan dengan list pada Python adalah konsumsi memory yang lebih kecil serta runtime yang lebih cepat. NumPy juga memudahkan kita pada Aljabar Linear, terutama operasi pada Vector (1-d array) dan Matrix (2-d array).

We will only learn the **basics** of NumPy, to get started we need to install it!

## Installation Instructions

Untuk Data Science dan Machine Learning sangat direkomendasikan menginstall Python dari distribusi Anaconda untuk memastikan semua dependensi dasar (seperti NumPy) tersinkronisasi dengan penggunaan *conda install*. 

Jika Anaconda sudah terinstal, instal NumPy dengan membuka terminal atau Anaconda Prompt (untuk Windows), lalu ketik:
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPY
Once you've installed NumPy you can import it as a library:

In [1]:
# run this cell (shift + enter)
import numpy as np

Numpy memiliki banyak *built-in functions* dan kapabilitas. Kita ga perlu tahu semuanya, tapi kita akan lebih fokus untuk mempelajari materi yang palng penting dari NumPy, yaitu:
- Vektor
- Array
- Matriks
- Number generation

# Numpy Arrays
NumPy arrays adalah hal utama untuk kita menggunakan NumPy. NumPy arrays terbagi menjadi 2 jenis, yaitu:
- Vektor&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Array yang hanya memiliki 1 dimensi (1-d array)
- Matriks&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Array 2 dimensi (2-d array)

(**nb : sebuah matriks juga bisa hanya memiliki 1 baris dan 1 kolom**)


## Vektor dan Matriks dalam Matematika

<img src='https://drive.google.com/uc?export=view&id=13Yz4BHwwdp8pD61qAx91JfQ8PIDHzME0' style= width:250px>

<img src='https://drive.google.com/uc?export=view&id=1JDXe74ZbwkT8bOjRWsEAO7t2xp43PsIA' style= width:300px>

<img src='https://drive.google.com/uc?export=view&id=1IfurOLRVJHCMbrAqTkOt3YjxjNMheDmI' style= width:400px>


- Vektor : Hanya mempunyai 1 baris atau 1 kolom, **identik dengan tipe data list pada Python**
- Matriks : Mempunyai beberapa baris (vertikal/menurun) dan kolom (horizontal/mendatar), cara membacanya adalah **baris x kolom**, **identik dengan nested list (list di dalam list) pada Python**

Baris x kolom dibaca ORDO, misal :
- Matriks nol pada gambar diatas mempunyai **ordo 2x2**
- Matriks persegi pada gambar diatas mempunyai **ordo 4x4**

## Creating NumPy Arrays
### From a Python List

Kita bisa membuat array dengan cara menggunakan atau mengkonversi list dari Python

In [6]:
list_python = [1,2,3,4,5,6]

# tampilkan output untuk mengecek dengan cara:
# print(my_list)
# atau
# my_list

type(list_python)

list

Gunakan method .array() untuk mengkonversi list menjadi array
dengan syntax
```python
np.array(list)
```

In [8]:
array_1d = np.array(list_python)
arr_1d = np.array([4,5,6,7,8,9]) # bisa juga langsung

print(array_1d)
print(type(array_1d))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
# Jumlah elemen di setiap list harus sama
my_matrix = [[13,5,4],[4,4,30],[11,22,4]] # benar
my_matriks = [[1,2,3],[4,5],[6,7,8,9],[10]] # salah

my_matrix

[[13, 5, 4], [4, 4, 30], [11, 22, 4]]

In [16]:
array_2d  = np.array(my_matrix) # akan menghasilkan matriks 3x3
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]) # akan menghasilkan matriks 5x4

arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

## NumPy Methods
Ada banyak cara untuk membuat array dengan NumPy method

### arange
Membuat array berdasarkan range (seperti range() di built-in fuction Python)

**syntax**:
```python
np.arange(start,stop,step=1)
```
nilai *default* step adalah 1

In [21]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [22]:
even_num = np.arange(0,21,2)
print(even_num)

[ 0  2  4  6  8 10 12 14 16 18 20]


### zeros and ones
Membuat array berisi angka 0 atau 1

In [25]:
np.zeros(5) # 1-d array atau vektor

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((30,50)) # 2-d array atau matriks

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Return array angka dengan interval yang spesifik

**syntax**:
```python
np.linspace(start,stop,num=50)
```
nilai default *num* adalah 50

In [36]:
np.linspace(50, 1000, 200)# menghasilkan array 50 angka dengan interval 1-25

array([  50.        ,   54.77386935,   59.54773869,   64.32160804,
         69.09547739,   73.86934673,   78.64321608,   83.41708543,
         88.19095477,   92.96482412,   97.73869347,  102.51256281,
        107.28643216,  112.06030151,  116.83417085,  121.6080402 ,
        126.38190955,  131.15577889,  135.92964824,  140.70351759,
        145.47738693,  150.25125628,  155.02512563,  159.79899497,
        164.57286432,  169.34673367,  174.12060302,  178.89447236,
        183.66834171,  188.44221106,  193.2160804 ,  197.98994975,
        202.7638191 ,  207.53768844,  212.31155779,  217.08542714,
        221.85929648,  226.63316583,  231.40703518,  236.18090452,
        240.95477387,  245.72864322,  250.50251256,  255.27638191,
        260.05025126,  264.8241206 ,  269.59798995,  274.3718593 ,
        279.14572864,  283.91959799,  288.69346734,  293.46733668,
        298.24120603,  303.01507538,  307.78894472,  312.56281407,
        317.33668342,  322.11055276,  326.88442211,  331.65829

In [30]:
np.linspace(0,10,5) # membuat array 5 angka dengan interval 0-10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.linspace(10,100,500) # membuat array 500 angka dengan interval 10-100

array([ 10.        ,  10.18036072,  10.36072144,  10.54108216,
        10.72144289,  10.90180361,  11.08216433,  11.26252505,
        11.44288577,  11.62324649,  11.80360721,  11.98396794,
        12.16432866,  12.34468938,  12.5250501 ,  12.70541082,
        12.88577154,  13.06613226,  13.24649299,  13.42685371,
        13.60721443,  13.78757515,  13.96793587,  14.14829659,
        14.32865731,  14.50901804,  14.68937876,  14.86973948,
        15.0501002 ,  15.23046092,  15.41082164,  15.59118236,
        15.77154309,  15.95190381,  16.13226453,  16.31262525,
        16.49298597,  16.67334669,  16.85370741,  17.03406814,
        17.21442886,  17.39478958,  17.5751503 ,  17.75551102,
        17.93587174,  18.11623246,  18.29659319,  18.47695391,
        18.65731463,  18.83767535,  19.01803607,  19.19839679,
        19.37875752,  19.55911824,  19.73947896,  19.91983968,
        20.1002004 ,  20.28056112,  20.46092184,  20.64128257,
        20.82164329,  21.00200401,  21.18236473,  21.36

### eye
Membuat matriks identitas

In [38]:
print(np.eye(4))
print()
print(np.eye(5))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Random
Numpy juga punya banyak cara untuk membuat array angka random:

### rand
Return array angka random dengan interval 0-1

In [37]:
# membuat 1-d array atau vektor
print(np.random.rand(2))
print(np.random.rand(4))

[0.47771411 0.49743724]
[0.82161968 0.42295976 0.99548827 0.3759756 ]


In [38]:
# membuat 2-d array atau matriks
print(np.random.rand(2,2))
print()
print(np.random.rand(4,4))

[[0.37753407 0.1920606 ]
 [0.11653374 0.36253656]]

[[0.68154015 0.09960092 0.60849054 0.91711158]
 [0.61419427 0.40573453 0.29056192 0.97847041]
 [0.91738389 0.67458102 0.46213213 0.80487363]
 [0.00223217 0.7166541  0.96118636 0.44824048]]


### randn
Return array angka random dengan distribusi normal

In [39]:
print(np.random.randn(2))
print(np.random.rand(4))

[-0.70847633  1.34546414]
[0.4433657  0.86717411 0.88473432 0.54419244]


In [41]:
print(np.random.randn(2,2))
print()
print(np.random.randn(3,3))

[[-1.34896295 -1.0956303 ]
 [-0.32547139  1.18677357]]

[[-0.23944674 -0.53986642 -0.33339821]
 [ 0.08019011 -0.49108997 -1.44037665]
 [ 1.57622245 -1.22709047 -0.08247453]]


### randint
Return random integer dari ```terkecil``` (inclusive) sampai ```terbesar``` (exclusive)

In [55]:
for i in range(100):
    print(np.random.randint(1,3))

1
1
1
2
2
2
1
1
1
1
2
2
1
1
1
1
2
2
1
1
2
1
1
1
2
1
1
2
2
1
2
1
2
1
1
1
1
1
1
1
1
1
1
1
2
2
2
1
2
2
1
2
1
2
2
2
2
1
2
1
2
2
1
2
1
2
1
1
2
2
1
1
1
1
2
1
1
2
2
2
1
2
2
1
1
2
2
1
1
2
2
1
1
1
2
2
1
1
2
2


In [57]:
# membuat array
print(np.random.randint(1,100, 5))

[42 37 52 68 38]


## Size and Shape attributes
Mengetahui jumlah angka dan Ordo(baris x kolom) dari suatu array

In [60]:
arr1 = np.array([1,2,3]) # vektor atau 1-d array
arr2 = np.array([[1,2,3],
                 [4,5,6]]) # matriks atau 2-d array
arr3 = np.random.rand(50,50) # matriks
arr4 = np.array([[1,2,3,4]]) # matriks
arr5 = np.array([[1],
                 [2],
                 [3],
                 [4]]) # matriks

In [68]:
print(f"array 1={arr1}\narray 2={arr2}")

array 1=[1 2 3]
array 2=[[1 2 3]
 [4 5 6]]


In [69]:
print("Ordo (baris, kolom) arr1 adalah {}".format(arr1.shape))
print("Ordo (baris, kolom) arr2 adalah {}".format(arr2.shape))
print("Ordo (baris, kolom) arr3 adalah {}".format(arr3.shape))
print("Ordo (baris, kolom) arr4 adalah {}".format(arr4.shape))
print("Ordo (baris, kolom) arr5 adalah {}".format(arr5.shape))

Ordo (baris, kolom) arr1 adalah (3,)
Ordo (baris, kolom) arr2 adalah (2, 3)
Ordo (baris, kolom) arr3 adalah (50, 50)
Ordo (baris, kolom) arr4 adalah (1, 4)
Ordo (baris, kolom) arr5 adalah (4, 1)


## Reshape
Merubah ordo (baris x kolom) dari suatu array

**PENTING**
Untuk me-reshape suatu array, baris x kolom **HARUS** sama dengan jumlah elemen/angkanya.
```row x column == array.size```

Misal : 
Jika kita mempunyai sebuah array yang didalamnya ada 10 angka maka kita hanya bisa me-reshape array tersebut menjadi :
- 1 x 10 (1 rows, 10 columns)
- 10 x 1 (10 rows, 1 columns)
- 5 x 2 (5 rows, 2 columns)
- 2 x 5 (2 rows, 5 columns)

In [71]:
arr1 = np.array([1,2,3]) # vektor atau 1-d array
arr2 = np.array([[1,2,3],
                 [4,5,6]]) # matriks atau 2-d array
arr3 = np.random.rand(50,50) # matriks
arr4 = np.array([[1,2,3,4]]) # matriks
arr5 = np.array([[1],
                 [2],
                 [3],
                 [4]]) # matriks

In [74]:
# vektor dirubah menjadi matriks
arr1 = arr1.reshape(1,3) 
# matriks diubah menjadi ordo atau bentuk yang berbeda
arr2 = arr2.reshape(3,2) 
arr3 = arr3.reshape(10,250)
arr4 = arr4.reshape(2,2)
# mengubah matriks menjadi vektor
arr5 = arr5.reshape(4,)

In [76]:
print(arr1)
print()
print(arr2)
print()
print(arr3)
print()
print(arr4)
print()
print(arr5)

[[1 2 3]]

[[1 2]
 [3 4]
 [5 6]]

[[0.34820688 0.39677005 0.28403873 ... 0.03012083 0.10195341 0.93559176]
 [0.6992127  0.145547   0.79147323 ... 0.98818767 0.09058118 0.76737931]
 [0.16746642 0.6309022  0.31984294 ... 0.21696585 0.21776332 0.18648772]
 ...
 [0.40128483 0.1262334  0.77672499 ... 0.80210981 0.07896417 0.92298331]
 [0.67800108 0.27674677 0.01347048 ... 0.00217632 0.69625922 0.293608  ]
 [0.82478579 0.76875195 0.29744291 ... 0.48876717 0.8426923  0.03338945]]

[[1 2]
 [3 4]]

[1 2 3 4]


## dtype
Mengetahui tipe data dari elemen yang ada di array

In [77]:
print(arr1.dtype)
print(arr3.dtype)

int32
float64


## max, min, argmax, argmin method
Max dan min digunakan untuk mengetahui angka terbesar atau terkecil dari sebuah array.

argmax dan argmin digunakan untuk mengetahui **index** angka terbesar atau terkecil dari sebuah array.

In [78]:
print(arr1)

[[1 2 3]]


In [81]:
print("Angka terbesar di arr1 adalah {} di index ke {}".format(arr1.max(),
                                                               arr1.argmax()))
print("Angka terkecil di arr1 adalah {} di index ke {}".format(arr1.min(),
                                                               arr1.argmin()))

Angka terbesar di arr1 adalah 3 di index ke 2
Angka terkecil di arr1 adalah 1 di index ke 0


# GREAT JOB!