<a href='https://nevtik.org'><img src='https://drive.google.com/uc?export=view&id=1_IP9MG7FF0p0Ah9q4ptR46StNwCSKFJV' style= width:100px></a>

# NumPy Indexing, Slicing, and Selection
Kali ini kita akan belajar bagaimana cara menyeleksi sebuah atau beberapa elemen dari suatu array

In [1]:
import numpy as np

In [15]:
# Creating sample array
arr = np.linspace(5,50,10)
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

## Bracket Indexing and Selection
Cara paling *simple* untuk memilih satu atau beberapa elemen dari array, caranya sama dengan list di Python biasa

In [16]:
# Get a value at an index
print(arr[8])

# Get values in a range (1)
print(arr[3:5])

# Get values in a range (2)
print(arr[0:7:2])



45.0
[20. 25.]
[ 5. 15. 25. 35.]


## Broadcasting
Salah satu kelebihan NumPy array dari pada list biasa adalah kemampuannya untuk melakukan *broadcasting assignment*

In [17]:
print("Array sebelum broadcasting assignment\t:\n",arr)

arr[2:9:2] = 100 # Assigning atau mengganti index ke 2-4 menjadi 3

print("\nArray setelah broadcasting assignment\t:\n",arr)

Array sebelum broadcasting assignment	:
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]

Array setelah broadcasting assignment	:
 [  5.  10. 100.  20. 100.  30. 100.  40. 100.  50.]


In [23]:
"""
Sekarang kita reset terlebih dahulu
array yang tadi dengan elemen 
yang baru agar lebih rapih
"""

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Dalam menggunakan slicing ada hal penting yang harus diperhatikan,
yaitu jika sebuah array terhubung dengan array lain maka setiap perubahan pada salah satu array akan mempengaruhi array yang lain

In [24]:
slice_of_arr = arr[2:]
slice_of_arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Replace all elements of slice_of_arr to 13
slice_of_arr[:] = 13
slice_of_arr

array([13, 13, 13, 13, 13, 13, 13, 13, 13])

Jika kita melakukan itu, array original-nya akan ikut terpengaruh, karena variabel ```arr``` dan ```slice_of_arr``` terletak di memori yang sama pada komputer

In [28]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
slice_of_arr = arr.copy()[2:]
slice_of_arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
slice_of_arr[:] = 13
slice_of_arr

array([13, 13, 13, 13, 13, 13, 13, 13, 13])

Untuk mencegahnya kita hanya perlu menggunakan cara copy array

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing and Slicing a 2D array (matrix)
Bisa dilakukan dengan 2 cara, yaitu:
1. **arr_2d[row][column]** (list syntax)
2. **arr_2d[row, column]** (NumPy syntax)

Tapi, saya merekomendasikan untuk menggunakan cara ke-2, yaitu menggunakan koma atau NumPy syntax

In [32]:
arr_1d = np.arange(0,15) # buat 1-d array dari 0-14
arr_2d = arr_1d.reshape(3,5) # reshape menjadi 2-d array ordo 3x5

# arr_2d = np.arange(0,15).reshape(3,5) <= Cara cepatnya (shortcut)

arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Sekarang kita akan melihat kelebihan dan kemudahan indexing dan slicing menggunakan koma (syntax numpy)

In [38]:
# Indexing row
# mengambil baris ke-2 (=index ke-1) dan semua kolom
print("Indexing row (baris):")
print(arr_2d[1]) # cara ke-1 (biasa)
print(arr_2d[:, 1:3]) # cara ke-2 (NumPy)

# Indexing column
# mengambil semua baris dan hanya kolom ke-4 (=index ke-3)
# print("\nIndexing column (kolom):")
print(np.array([i[3] for i in arr_2d])) # cara ke-1 (biasa)
print(arr_2d[:,3]) # cara ke-2 (NumPy)

Indexing row (baris):
[5 6 7 8 9]
[[ 1  2]
 [ 6  7]
 [11 12]]
[ 3  8 13]
[ 3  8 13]


In [41]:
# Getting individual element
# print(arr_2d[1][3])
print(arr_2d[2,3])

13


In [66]:
# 2d array slicing
# mengambil baris ke 1-2 (index 0-1) dan kolom ke 2-3 (index 1-2)
arr_2d[:2,1:3] # atau arr_2d[0:2, 1:3]

array([[1, 2],
       [6, 7]])

In [43]:
# contoh lain (amati dan pahami)
arr_2d[:1, :2]

array([[0, 1]])

## hstack and vstack
- hstack : digunakan untuk menumpuk array secara horizontal =>syntax: np.hstack((arr1,arr2))
- vstack : digunakan untuk menumpuk array secara vertikal =>syntax: np.vstack((arr1,arr2))


In [47]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack((arr1,arr2)))
np.vstack((arr1,arr2))

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

# GREAT JOB! 
Next to NumPy Operations